- op: replace #action 
  path: /metadata/name
  value: prod-svc


# apiVersion: v1
# kind: Service
# metadata:
#   name: prod-svc  #  production svc name
#   labels:
#     app: gapcloud
#     env: prod
# spec:
#   selector:
#     app: gapcloud
#     env: prod
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080