- op: replace #action 
  path: /metadata/name
  value: staging-deployment

- op: replace #action 
  path: /spec/replicas
  value: 1

# - op: replace #action 
#   path: spec/selector/matchLabels/env
#   value: staging

# - op: replace #action 
#   path: spec/template/metadata/labels/env
#   value: staging


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: staging-deployment
#   labels:
#     app: gapcloud
#     env: staging
# spec:
#   replicas: 1 #
#   selector:
#     matchLabels:
#       app: gapcloud
#       env: staging
#   template:
#     metadata:
#       labels:
#         app: gapcloud
#         env: staging
#     spec:
#       containers:
#       - name: gapcloud
#         image: gapcloud-staging-image:test
#         ports:
#         - containerPort: 8080
#           name: gapcloud-app-port  




